-- Notifications, saved filters, dashboards, gadgets and audit log.

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    type        VARCHAR(30)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    message     TEXT,
    entity_type VARCHAR(50),
    entity_id   BIGINT,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_user ON notifications (user_id, is_read);

CREATE TABLE saved_filters (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT        NOT NULL,
    name       VARCHAR(150)  NOT NULL,
    query      VARCHAR(2000) NOT NULL,
    shared     BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ   NOT NULL,
    updated_at TIMESTAMPTZ   NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_saved_filters_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE dashboards (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL,
    name       VARCHAR(150) NOT NULL,
    shared     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_dashboards_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE dashboard_gadgets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_id BIGINT      NOT NULL,
    gadget_type  VARCHAR(50) NOT NULL,
    config       TEXT,
    position     INTEGER     NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    created_by   BIGINT,
    updated_by   BIGINT,
    CONSTRAINT fk_dashboard_gadgets_dashboard FOREIGN KEY (dashboard_id) REFERENCES dashboards (id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id   BIGINT,
    action      VARCHAR(50) NOT NULL,
    actor_id    BIGINT,
    details     TEXT,
    created_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
