-- Projects, project membership and the per-project issue sequence counter.

CREATE TABLE projects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    project_key     VARCHAR(20)  NOT NULL UNIQUE,
    name            VARCHAR(150) NOT NULL,
    description     VARCHAR(1000),
    lead_id         BIGINT,
    workflow_id     BIGINT,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    created_by      BIGINT,
    updated_by      BIGINT,
    CONSTRAINT fk_projects_org FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE project_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    role       VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uq_project_members UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE project_issue_seq (
    project_id BIGINT NOT NULL PRIMARY KEY,
    seq        BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_project_issue_seq_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);
