-- Issue metadata lookups: types, priorities and statuses.

CREATE TABLE issue_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200),
    icon        VARCHAR(50),
    subtask     BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE priorities (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL UNIQUE,
    level INTEGER     NOT NULL,
    color VARCHAR(20)
);

CREATE TABLE statuses (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(20) NOT NULL
);
