-- Workflow definitions, their statuses and permitted transitions.

CREATE TABLE workflows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  BIGINT,
    updated_by  BIGINT
);

CREATE TABLE workflow_statuses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT  NOT NULL,
    status_id   BIGINT  NOT NULL,
    is_initial  BOOLEAN NOT NULL DEFAULT FALSE,
    position    INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_workflow_statuses UNIQUE (workflow_id, status_id),
    CONSTRAINT fk_workflow_statuses_workflow FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_statuses_status FOREIGN KEY (status_id) REFERENCES statuses (id)
);

CREATE TABLE workflow_transitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id    BIGINT       NOT NULL,
    from_status_id BIGINT,
    to_status_id   BIGINT       NOT NULL,
    name           VARCHAR(100) NOT NULL,
    CONSTRAINT fk_workflow_transitions_workflow FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_transitions_from FOREIGN KEY (from_status_id) REFERENCES statuses (id),
    CONSTRAINT fk_workflow_transitions_to FOREIGN KEY (to_status_id) REFERENCES statuses (id)
);
CREATE INDEX idx_workflow_transitions_lookup ON workflow_transitions (workflow_id, from_status_id, to_status_id);
