-- Core issue table.

CREATE TABLE issues (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT       NOT NULL,
    issue_key     VARCHAR(40)  NOT NULL UNIQUE,
    summary       VARCHAR(255) NOT NULL,
    description   TEXT,
    issue_type_id BIGINT       NOT NULL,
    priority_id   BIGINT       NOT NULL,
    status_id     BIGINT       NOT NULL,
    reporter_id   BIGINT       NOT NULL,
    assignee_id   BIGINT,
    parent_id     BIGINT,
    sprint_id     BIGINT,
    story_points  INTEGER,
    due_date      DATE,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    CONSTRAINT fk_issues_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_issues_type FOREIGN KEY (issue_type_id) REFERENCES issue_types (id),
    CONSTRAINT fk_issues_priority FOREIGN KEY (priority_id) REFERENCES priorities (id),
    CONSTRAINT fk_issues_status FOREIGN KEY (status_id) REFERENCES statuses (id),
    CONSTRAINT fk_issues_reporter FOREIGN KEY (reporter_id) REFERENCES users (id),
    CONSTRAINT fk_issues_assignee FOREIGN KEY (assignee_id) REFERENCES users (id),
    CONSTRAINT fk_issues_parent FOREIGN KEY (parent_id) REFERENCES issues (id)
);
CREATE INDEX idx_issues_project ON issues (project_id);
CREATE INDEX idx_issues_status ON issues (status_id);
CREATE INDEX idx_issues_assignee ON issues (assignee_id);
CREATE INDEX idx_issues_sprint ON issues (sprint_id);
CREATE INDEX idx_issues_parent ON issues (parent_id);
