-- Components and the issue/component join table.

CREATE TABLE components (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    lead_id     BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  BIGINT,
    updated_by  BIGINT,
    CONSTRAINT uq_components_project_name UNIQUE (project_id, name),
    CONSTRAINT fk_components_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE issue_components (
    issue_id     BIGINT NOT NULL,
    component_id BIGINT NOT NULL,
    PRIMARY KEY (issue_id, component_id),
    CONSTRAINT fk_issue_components_issue FOREIGN KEY (issue_id) REFERENCES issues (id) ON DELETE CASCADE,
    CONSTRAINT fk_issue_components_component FOREIGN KEY (component_id) REFERENCES components (id) ON DELETE CASCADE
);
