-- Sprints.

CREATE TABLE sprints (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL,
    name       VARCHAR(150) NOT NULL,
    goal       VARCHAR(1000),
    state      VARCHAR(20)  NOT NULL DEFAULT 'FUTURE',
    start_date TIMESTAMPTZ,
    end_date   TIMESTAMPTZ,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_sprints_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);
CREATE INDEX idx_sprints_project ON sprints (project_id);
