-- Boards and their columns.

CREATE TABLE boards (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL,
    name       VARCHAR(150) NOT NULL,
    board_type VARCHAR(20)  NOT NULL DEFAULT 'SCRUM',
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_boards_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE board_columns (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id   BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    status_id  BIGINT       NOT NULL,
    position   INTEGER      NOT NULL DEFAULT 0,
    wip_limit  INTEGER,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_board_columns_board FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE,
    CONSTRAINT fk_board_columns_status FOREIGN KEY (status_id) REFERENCES statuses (id)
);
CREATE INDEX idx_board_columns_board ON board_columns (board_id);
